// ============================================================
// 工作模式精选 Seed 数据
//
// 说明：Phase 2 采用"先精选数据、后接数据库"策略。
// 这些是杭州地区知名科技公司的公开位置信息与示例岗位，
// 用于验证工作模式的 UI/筛选/联动逻辑。
//
// 数据合规（tech/08-multi-mode-system.md + agent.md）：
// - 公司位置为公开地理信息，岗位为代表性示例（非实时爬取）
// - 不包含个人简历、联系方式等 PII
// - 生产环境将替换为经 source review 的数据库数据（sources/import_runs）
// ============================================================

import { resolveCompanyLogo } from './company-logo.ts';
import { defaultTaxonomyForType } from './job-taxonomy.ts';
import type { DomainPOI, RecruitmentPOI } from './types.ts';

/**
 * Domain 模式回退种子数据。
 * 用途：AMap JS API 不可用/加载失败时的降级方案（例如首次加载插件竞态、
 * 网络受限环境）。AMap 就绪后，poi-service 会优先返回真实高德 POI。
 * 位置为杭州代表性地点的公开地理信息。
 */
export const DOMAIN_SEED: DomainPOI[] = [
  {
    id: 'hz-westlake',
    kind: 'domain',
    name: '西湖',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.15, lat: 30.242, address: '西湖区龙井路1号' },
    category: '景点',
    subcategory: '自然风光',
    rating: 4.9,
    photos: [],
  },
  {
    id: 'hz-in77',
    kind: 'domain',
    name: '湖滨银泰in77',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.163, lat: 30.256, address: '上城区延安路湖滨' },
    category: '购物',
    subcategory: '购物中心',
    rating: 4.6,
    priceLevel: 3,
    photos: [],
  },
  {
    id: 'hz-louwailou',
    kind: 'domain',
    name: '楼外楼菜馆',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.141, lat: 30.237, address: '西湖区孤山路30号' },
    category: '餐饮',
    subcategory: '杭帮菜',
    rating: 4.3,
    priceLevel: 3,
    openHours: '10:30-21:00',
    photos: [],
  },
  {
    id: 'hz-lingyin',
    kind: 'domain',
    name: '灵隐寺',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.105, lat: 30.24, address: '西湖区法云弄1号' },
    category: '景点',
    subcategory: '佛教文化',
    rating: 4.8,
    photos: [],
  },
  {
    id: 'hz-yinyuequan',
    kind: 'domain',
    name: '音乐泉SPA',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.152, lat: 30.26, address: '西湖区西溪路128号' },
    category: '休闲娱乐',
    subcategory: 'SPA',
    rating: 4.2,
    priceLevel: 4,
    photos: [],
  },
  {
    id: 'hz-wulinsi',
    kind: 'domain',
    name: '武林广场',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.166, lat: 30.269, address: '下城区武林广场' },
    category: '购物',
    subcategory: '商业街区',
    rating: 4.4,
    photos: [],
  },
  {
    id: 'hz-songcheng',
    kind: 'domain',
    name: '杭州宋城',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.083, lat: 30.176, address: '西湖区之江路148号' },
    category: '景点',
    subcategory: '主题公园',
    rating: 4.5,
    priceLevel: 3,
    photos: [],
  },
  {
    id: 'hz-hefangjie',
    kind: 'domain',
    name: '河坊街',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.173, lat: 30.242, address: '上城区河坊街' },
    category: '美食街',
    subcategory: '特色小吃',
    rating: 4.4,
    priceLevel: 2,
    photos: [],
  },
  {
    id: 'hz-xihu-museum',
    kind: 'domain',
    name: '浙江博物馆',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.146, lat: 30.238, address: '西湖区孤山路25号' },
    category: '文化',
    subcategory: '博物馆',
    rating: 4.6,
    photos: [],
  },
];

const WORK_SEED_RAW: RecruitmentPOI[] = [
  {
    id: 'alibaba-xixi',
    kind: 'recruitment',
    name: '阿里巴巴',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.024, lat: 30.275, address: '余杭区文一西路969号' },
    company: {
      name: '阿里巴巴',
      industries: ['internet', 'ecommerce', 'ai'],
      scale: 'bigtech',
      rating: 4.4,
      logo: '🛰️',
      logoUrl: 'https://favicon.im/alibaba.com?size=128',
      summary: '全球领先的电子商务与云计算科技公司',
      careerUrl: 'https://talent.alibaba.com/',
    },
    positions: [
      {
        id: 'alibaba-java',
        title: 'Java 后端开发工程师',
        department: '阿里云',
        type: 'intern',
        taxonomy: { family: 'intern', internKind: 'summer', conversion: 'conversion' },
        salary: { min: 8, max: 15 },
        education: '本科',
        majors: ['计算机', '软件工程'],
        skills: ['Java', 'Spring', 'MySQL'],
        description: '参与阿里云核心服务的后端开发，编写高质量 Java 服务，参与需求评审与线上问题排查。熟悉分布式系统优先。',
        apply: { source: 'official', url: 'https://talent.alibaba.com/' },
        status: 'open',
      },
      {
        id: 'alibaba-frontend',
        title: '前端开发工程师',
        department: '淘天集团',
        type: 'intern',
        taxonomy: { family: 'intern', internKind: 'daily', conversion: 'no-conversion' },
        salary: { min: 8, max: 14 },
        education: '本科',
        majors: ['计算机'],
        skills: ['React', 'TypeScript'],
        description: '负责淘天 C 端页面与中后台的前端实现，与设计、后端协作完成需求交付，关注性能与体验。',
        status: 'open',
      },
      {
        id: 'alibaba-ml',
        title: '算法工程师（机器学习）',
        department: '达摩院',
        type: 'intern',
        salary: { min: 10, max: 20 },
        education: '硕士',
        majors: ['计算机', '数学'],
        skills: ['Python', 'PyTorch'],
        description: '参与推荐 / 搜索相关模型训练与评测，阅读论文并落地实验，协助完成数据pipeline 与指标分析。',
        status: 'open',
      },
      {
        id: 'alibaba-product',
        title: '产品经理实习生',
        department: '国际数字商业',
        type: 'intern',
        salary: { min: 6, max: 10 },
        education: '本科',
        description: '协助完成竞品分析、需求文档与用户调研，跟进功能上线，与设计、研发协作推进迭代。',
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车', '健身房', '节日福利'],
  },
  {
    id: 'tencent-hangzhou',
    kind: 'recruitment',
    name: '腾讯',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.155, lat: 30.307, address: '滨江区网商路599号' },
    company: {
      name: '腾讯',
      industries: ['internet', 'game', 'ai'],
      scale: 'bigtech',
      rating: 4.5,
      logo: '🐧',
      logoUrl: 'https://favicon.im/tencent.com?size=128',
      summary: '中国领先的互联网综合服务提供商',
      careerUrl: 'https://careers.tencent.com/',
    },
    positions: [
      {
        id: 'tencent-backend',
        title: '后台开发工程师',
        department: '腾讯云',
        type: 'campus',
        taxonomy: { family: 'campus', campusSeason: 'autumn' },
        salary: { min: 9, max: 16 },
        education: '本科',
        majors: ['计算机'],
        skills: ['C++', 'Go'],
        status: 'open',
      },
      {
        id: 'tencent-game',
        title: '游戏策划实习生',
        department: '天美工作室',
        type: 'intern',
        salary: { min: 6, max: 10 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车', '下午茶'],
  },
  {
    id: 'netease-hangzhou',
    kind: 'recruitment',
    name: '网易',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.189, lat: 30.187, address: '滨江区网商路599号网易大厦' },
    company: {
      name: '网易',
      industries: ['internet', 'game'],
      scale: 'bigtech',
      rating: 4.3,
      logo: '🎮',
      logoUrl: 'https://favicon.im/163.com?size=128',
      summary: '中国领先的互联网技术公司，游戏与音乐见长',
      careerUrl: 'https://hr.163.com/',
    },
    positions: [
      {
        id: 'netease-frontend',
        title: '前端开发工程师',
        department: '网易云音乐',
        type: 'campus',
        taxonomy: { family: 'campus', campusSeason: 'spring' },
        salary: { min: 7, max: 12 },
        education: '本科',
        skills: ['React', 'TypeScript'],
        status: 'open',
      },
      {
        id: 'netease-data',
        title: '数据分析师',
        department: '严选',
        type: 'intern',
        salary: { min: 6, max: 10 },
        education: '本科',
        majors: ['统计', '数学'],
        skills: ['SQL', 'Python'],
        status: 'open',
      },
    ],
    benefits: ['免费班车', '健身房', '咖啡'],
  },
  {
    id: 'bytedance-hangzhou',
    kind: 'recruitment',
    name: '字节跳动',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.003, lat: 30.281, address: '余杭区向往街1118号' },
    company: {
      name: '字节跳动',
      industries: ['internet', 'ai', 'ecommerce'],
      scale: 'bigtech',
      rating: 4.6,
      logo: '📱',
      logoUrl: 'https://favicon.im/bytedance.com?size=128',
      summary: '全球化互联网科技公司，抖音/TikTok 母公司',
      careerUrl: 'https://jobs.bytedance.com/',
    },
    positions: [
      {
        id: 'bytedance-algo',
        title: '推荐算法工程师',
        department: '抖音',
        type: 'intern',
        salary: { min: 10, max: 18 },
        education: '硕士',
        majors: ['计算机'],
        skills: ['Python', '推荐系统'],
        status: 'open',
      },
      {
        id: 'bytedance-ios',
        title: 'iOS 开发工程师',
        department: '抖音',
        type: 'intern',
        salary: { min: 9, max: 16 },
        education: '本科',
        skills: ['Swift', 'Objective-C'],
        status: 'open',
      },
      {
        id: 'bytedance-ops',
        title: '产品运营实习生',
        department: '商业化',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['三餐免费', '免费班车', '健身房', '补充医疗'],
  },
  {
    id: 'huawei-hangzhou',
    kind: 'recruitment',
    name: '华为',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.098, lat: 30.306, address: '滨江区江淑路1000号' },
    company: {
      name: '华为',
      industries: ['hardware', 'ai'],
      scale: 'bigtech',
      rating: 4.2,
      logo: '🌍',
      logoUrl: 'https://favicon.im/huawei.com?size=128',
      summary: '全球领先的 ICT 基础设施与智能终端提供商',
      careerUrl: 'https://career.huawei.com/',
    },
    positions: [
      {
        id: 'huawei-chip',
        title: '芯片设计工程师',
        department: '海思',
        type: 'social',
        taxonomy: { family: 'social', experience: '1-3' },
        salary: { min: 9, max: 15 },
        education: '硕士',
        majors: ['微电子', '电子工程'],
        apply: { source: 'official', url: 'https://career.huawei.com/' },
        status: 'open',
      },
      {
        id: 'huawei-embedded',
        title: '嵌入式软件工程师',
        department: '2012实验室',
        type: 'intern',
        salary: { min: 8, max: 14 },
        education: '本科',
        skills: ['C', 'Linux'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车', '健身房'],
  },
  {
    id: 'antgroup-hangzhou',
    kind: 'recruitment',
    name: '蚂蚁集团',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.108, lat: 30.267, address: '西湖区西溪路556号蚂蚁Z空间' },
    company: {
      name: '蚂蚁集团',
      industries: ['finance', 'internet'],
      scale: 'bigtech',
      rating: 4.3,
      logo: '🐜',
      logoUrl: 'https://favicon.im/antgroup.com?size=128',
      summary: '领先的数字支付与金融科技公司',
      careerUrl: 'https://talent.antgroup.com/',
    },
    positions: [
      {
        id: 'ant-pay',
        title: '支付后端工程师',
        department: '支付宝',
        type: 'social',
        taxonomy: { family: 'social', experience: '3-5' },
        salary: { min: 9, max: 16 },
        education: '本科',
        skills: ['Java', '分布式'],
        status: 'open',
      },
      {
        id: 'ant-blockchain',
        title: '区块链研发实习生',
        department: '蚂蚁链',
        type: 'intern',
        salary: { min: 8, max: 14 },
        education: '硕士',
        skills: ['Go', 'Rust'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车', '健身'],
  },
  {
    id: 'didi-hangzhou',
    kind: 'recruitment',
    name: '滴滴',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.003, lat: 30.281, address: '余杭区景兴路896号欧美金融城(EFC)' },
    company: {
      name: '滴滴',
      industries: ['internet', 'transport'],
      scale: 'unicorn',
      rating: 4.0,
      logo: '🚗',
      logoUrl: 'https://favicon.im/didiglobal.com?size=128',
      summary: '一站式移动出行平台',
      careerUrl: 'https://join.didiglobal.com/',
    },
    positions: [
      {
        id: 'didi-map',
        title: '地图算法实习生',
        department: '地图事业部',
        type: 'social',
        taxonomy: { family: 'social', experience: '0-1' },
        salary: { min: 7, max: 12 },
        education: '硕士',
        skills: ['C++', 'GIS'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车'],
  },
  {
    id: 'zhihu-hangzhou',
    kind: 'recruitment',
    name: '知乎',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.162, lat: 30.258, address: '西湖区文三路90号东部软件园' },
    company: {
      name: '知乎',
      industries: ['internet', 'ai'],
      scale: 'unicorn',
      rating: 4.1,
      logo: '🧠',
      logoUrl: 'https://favicon.im/zhihu.com?size=128',
      summary: '中文互联网高质量问答社区',
      careerUrl: 'https://www.zhihu.com/careers',
    },
    positions: [
      {
        id: 'zhihu-nlp',
        title: 'NLP 算法实习生',
        department: 'AI 中心',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '硕士',
        skills: ['Python', 'NLP'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '下午茶'],
  },
  {
    id: 'xixi-ai',
    kind: 'recruitment',
    name: '曦曦AI',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.158, lat: 30.288, address: '余杭区未来科技城' },
    company: {
      name: '曦曦AI',
      industries: ['ai'],
      scale: 'startup',
      rating: 4.0,
      logo: '✨',
      summary: '专注生成式 AI 应用的新锐创业公司',
    },
    positions: [
      {
        id: 'xixi-llm',
        title: '大模型应用开发实习生',
        department: '工程',
        type: 'intern',
        salary: { min: 8, max: 15 },
        education: '本科',
        skills: ['Python', 'LLM', 'RAG'],
        apply: {
          source: 'boss',
          url: 'https://www.zhipin.com/web/geek/job?query=%E6%9B%A6%E6%9B%A6AI%20%E5%A4%A7%E6%A8%A1%E5%9E%8B',
        },
        status: 'open',
      },
    ],
    benefits: ['弹性工作', '股权激励'],
  },
  {
    id: 'deepseek',
    kind: 'recruitment',
    name: '深度求索',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.173, lat: 30.274, address: '拱墅区环城北路169号汇金国际大厦' },
    company: {
      name: '深度求索',
      industries: ['ai'],
      scale: 'unicorn',
      rating: 4.7,
      logo: '🧩',
      logoUrl: 'https://favicon.im/deepseek.com?size=128',
      summary: 'AI 大模型研发公司，DeepSeek 团队',
      careerUrl: 'https://www.deepseek.com/',
    },
    positions: [
      {
        id: 'deepseek-llm',
        title: '大模型训练实习生',
        department: '研发',
        type: 'intern',
        taxonomy: { family: 'intern', internKind: 'summer', conversion: 'conversion' },
        salary: { min: 12, max: 25 },
        education: '硕士',
        majors: ['计算机', '数学'],
        skills: ['Python', 'PyTorch', '分布式训练'],
        status: 'open',
      },
      {
        id: 'deepseek-infra',
        title: 'AI Infra 工程师',
        department: '基础设施',
        type: 'intern',
        salary: { min: 10, max: 20 },
        education: '本科',
        skills: ['C++', 'CUDA'],
        status: 'open',
      },
    ],
    benefits: ['免费三餐', '顶尖算力'],
  },
  {
    id: 'bilibili-hangzhou',
    kind: 'recruitment',
    name: '哔哩哔哩',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.192, lat: 30.273, address: '西湖区转塘科技园区' },
    company: {
      name: '哔哩哔哩',
      industries: ['internet', 'game'],
      scale: 'bigtech',
      rating: 4.5,
      logo: '📺',
      logoUrl: 'https://favicon.im/bilibili.com?size=128',
      summary: '中国年轻世代高度聚集的文化社区和视频平台',
      careerUrl: 'https://jobs.bilibili.com/',
    },
    positions: [
      {
        id: 'bili-community',
        title: '社区运营实习生',
        department: '社区',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['免费班车', '员工餐厅'],
  },
  {
    id: 'futu-hangzhou',
    kind: 'recruitment',
    name: '富途',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.168, lat: 30.247, address: '西湖区古荡街道' },
    company: {
      name: '富途',
      industries: ['finance', 'internet'],
      scale: 'enterprise',
      rating: 4.1,
      logo: '📈',
      logoUrl: 'https://favicon.im/futunn.com?size=128',
      summary: '一站式数字化金融服务平台',
      careerUrl: 'https://careers.futunn.com/',
    },
    positions: [
      {
        id: 'futu-backend',
        title: '量化系统后端实习生',
        department: '交易系统',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '本科',
        skills: ['Java', 'C++'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '健身房'],
  },
  {
    id: 'hikvision-hangzhou',
    kind: 'recruitment',
    name: '海康威视',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.208, lat: 30.185, address: '滨江区阡陌路555号' },
    company: {
      name: '海康威视',
      industries: ['hardware', 'ai'],
      scale: 'enterprise',
      rating: 4.0,
      logo: '📹',
      logoUrl: 'https://favicon.im/hikvision.com?size=128',
      summary: '全球领先的智能物联解决方案提供商',
      careerUrl: 'https://career.hikvision.com/',
    },
    positions: [
      {
        id: 'hik-vision',
        title: '计算机视觉算法实习生',
        department: '研究院',
        type: 'intern',
        salary: { min: 7, max: 13 },
        education: '硕士',
        skills: ['Python', 'CV'],
        status: 'open',
      },
    ],
    benefits: ['免费班车', '员工食堂'],
  },
  {
    id: 'megvii-hangzhou',
    kind: 'recruitment',
    name: '旷视科技',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.112, lat: 30.288, address: '西湖区文一西路98号数娱大厦' },
    company: {
      name: '旷视科技',
      industries: ['ai', 'hardware'],
      scale: 'unicorn',
      rating: 4.0,
      logo: '👁️',
      logoUrl: 'https://favicon.im/megvii.com?size=128',
      summary: '聚焦物联网场景的人工智能公司',
      careerUrl: 'https://www.megvii.com/careers',
    },
    positions: [
      {
        id: 'megvii-face',
        title: '人脸识别算法实习生',
        department: '研究院',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '硕士',
        skills: ['Python', 'CV'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '弹性工作'],
  },
  {
    id: 'yuewen-hangzhou',
    kind: 'recruitment',
    name: '阅文集团',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.117, lat: 30.283, address: '余杭区文一西路998号' },
    company: {
      name: '阅文集团',
      industries: ['internet', 'content'],
      scale: 'enterprise',
      rating: 3.9,
      logo: '📚',
      logoUrl: 'https://favicon.im/yuewen.com?size=128',
      summary: '中国领先的网络文学平台',
      careerUrl: 'https://join.yuewen.com/',
    },
    positions: [
      {
        id: 'yuewen-editor',
        title: '内容运营实习生',
        department: '起点读书',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'cainiao-hangzhou',
    kind: 'recruitment',
    name: '菜鸟',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.026, lat: 30.278, address: '余杭区菜鸟总部园区' },
    company: {
      name: '菜鸟',
      industries: ['internet', 'transport'],
      scale: 'bigtech',
      rating: 4.1,
      logo: '📦',
      logoUrl: 'https://favicon.im/cainiao.com?size=128',
      summary: '全球化物流产业互联网公司',
      careerUrl: 'https://careers.cainiao.com/',
    },
    positions: [
      {
        id: 'cainiao-algo',
        title: '物流算法实习生',
        department: '调度',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '本科',
        skills: ['Python', '运筹'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车'],
  },
  {
    id: 'hundsun-hangzhou',
    kind: 'recruitment',
    name: '恒生电子',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.124, lat: 30.287, address: '滨江区江南大道3588号恒生大厦' },
    company: {
      name: '恒生电子',
      industries: ['finance', 'internet'],
      scale: 'enterprise',
      rating: 3.9,
      logo: '💹',
      logoUrl: 'https://favicon.im/hundsun.com?size=128',
      summary: '金融科技解决方案提供商',
      careerUrl: 'https://career.hundsun.com/',
    },
    positions: [
      {
        id: 'hundsun-java',
        title: '金融软件开发工程师',
        department: '财富事业部',
        type: 'campus',
        taxonomy: { family: 'campus', campusSeason: 'autumn' },
        salary: { min: 8, max: 14 },
        education: '本科',
        skills: ['Java'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '补充医疗'],
  },
  {
    id: 'hithink-hangzhou',
    kind: 'recruitment',
    name: '同花顺',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.046, lat: 30.293, address: '余杭区同顺街18号' },
    company: {
      name: '同花顺',
      industries: ['finance', 'internet'],
      scale: 'enterprise',
      rating: 3.8,
      logo: '📊',
      logoUrl: 'https://favicon.im/10jqka.com.cn?size=128',
      summary: '互联网金融信息服务商',
      careerUrl: 'https://job.10jqka.com.cn/',
    },
    positions: [
      {
        id: 'hithink-fe',
        title: '前端开发实习生',
        department: '爱基金',
        type: 'intern',
        salary: { min: 5, max: 9 },
        education: '本科',
        skills: ['Vue', 'TypeScript'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '下午茶'],
  },
  {
    id: 'youzan-hangzhou',
    kind: 'recruitment',
    name: '有赞',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.101, lat: 30.289, address: '西湖区西溪路698号华泰创业园' },
    company: {
      name: '有赞',
      industries: ['ecommerce', 'internet'],
      scale: 'unicorn',
      rating: 3.8,
      logo: '🛍️',
      logoUrl: 'https://favicon.im/youzan.com?size=128',
      summary: '商家数字化解决方案服务商',
      careerUrl: 'https://job.youzan.com/',
    },
    positions: [
      {
        id: 'youzan-backend',
        title: 'Java 开发实习生',
        department: '零售中台',
        type: 'intern',
        salary: { min: 5, max: 9 },
        education: '本科',
        skills: ['Java', 'Spring'],
        status: 'open',
      },
    ],
    benefits: ['弹性工作', '餐补'],
  },
  {
    id: 'dahua-hangzhou',
    kind: 'recruitment',
    name: '大华股份',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.219, lat: 30.189, address: '滨江区滨安路1187号' },
    company: {
      name: '大华股份',
      industries: ['hardware', 'ai'],
      scale: 'enterprise',
      rating: 3.9,
      logo: '🎥',
      logoUrl: 'https://favicon.im/dahuatech.com?size=128',
      summary: '以视频为核心的智慧物联解决方案提供商',
      careerUrl: 'https://www.dahuatech.com/careers.html',
    },
    positions: [
      {
        id: 'dahua-embedded',
        title: '嵌入式软件实习生',
        department: '研发中心',
        type: 'intern',
        salary: { min: 6, max: 10 },
        education: '本科',
        skills: ['C', 'Linux'],
        status: 'open',
      },
    ],
    benefits: ['班车', '食堂'],
  },
  {
    id: 'h3c-hangzhou',
    kind: 'recruitment',
    name: '新华三',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.198, lat: 30.185, address: '滨江区长河路466号' },
    company: {
      name: '新华三',
      industries: ['hardware', 'internet'],
      scale: 'enterprise',
      rating: 4.0,
      logo: '🖧',
      logoUrl: 'https://favicon.im/h3c.com?size=128',
      summary: '数字化解决方案领导者',
      careerUrl: 'https://career.h3c.com/',
    },
    positions: [
      {
        id: 'h3c-network',
        title: '网络设备软件工程师',
        department: '交换机产品线',
        type: 'campus',
        taxonomy: { family: 'campus', campusSeason: 'autumn' },
        salary: { min: 8, max: 14 },
        education: '本科',
        skills: ['C', '网络协议'],
        status: 'open',
      },
    ],
    benefits: ['班车', '食堂'],
  },
  {
    id: 'supcon-hangzhou',
    kind: 'recruitment',
    name: '中控技术',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.123, lat: 30.266, address: '滨江区六和路309号' },
    company: {
      name: '中控技术',
      industries: ['hardware', 'ai'],
      scale: 'enterprise',
      rating: 3.9,
      logo: '🏭',
      logoUrl: 'https://favicon.im/supcon.com?size=128',
      summary: '工业自动化与智能制造公司',
      careerUrl: 'https://www.supcon.com/careers',
    },
    positions: [
      {
        id: 'supcon-control',
        title: '工控软件实习生',
        department: '控制系统',
        type: 'intern',
        salary: { min: 5, max: 9 },
        education: '本科',
        skills: ['C#', 'PLC'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'geely-hangzhou',
    kind: 'recruitment',
    name: '吉利汽车',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.075, lat: 30.296, address: '滨江区江陵路1760号' },
    company: {
      name: '吉利汽车',
      industries: ['automotive'],
      scale: 'enterprise',
      rating: 4.0,
      logo: '🚘',
      logoUrl: 'https://favicon.im/geely.com?size=128',
      summary: '中国领先的汽车集团',
      careerUrl: 'https://campus.geely.com/',
    },
    positions: [
      {
        id: 'geely-ee',
        title: '智能驾驶软件工程师',
        department: '极氪智能',
        type: 'campus',
        taxonomy: { family: 'campus', campusSeason: 'autumn' },
        salary: { min: 9, max: 16 },
        education: '本科',
        skills: ['C++', 'ROS'],
        status: 'open',
      },
    ],
    benefits: ['班车', '食堂'],
  },
  {
    id: 'leapmotor-hangzhou',
    kind: 'recruitment',
    name: '零跑汽车',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.221, lat: 30.208, address: '滨江区物联网街451号' },
    company: {
      name: '零跑汽车',
      industries: ['automotive', 'ai'],
      scale: 'unicorn',
      rating: 3.9,
      logo: '⚡',
      logoUrl: 'https://favicon.im/leapmotor.com?size=128',
      summary: '智能电动汽车公司',
      careerUrl: 'https://www.leapmotor.com/career',
    },
    positions: [
      {
        id: 'leap-ad',
        title: '智驾算法实习生',
        department: '智能驾驶',
        type: 'intern',
        salary: { min: 7, max: 13 },
        education: '硕士',
        skills: ['Python', 'CV'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '班车'],
  },
  {
    id: 'dxy-hangzhou',
    kind: 'recruitment',
    name: '丁香园',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.129, lat: 30.276, address: '西湖区西溪路778号' },
    company: {
      name: '丁香园',
      industries: ['biotech', 'internet'],
      scale: 'unicorn',
      rating: 4.1,
      logo: '🌿',
      logoUrl: 'https://favicon.im/dxy.cn?size=128',
      summary: '连接医疗从业者的数字化健康平台',
      careerUrl: 'https://www.dxy.cn/jobs',
    },
    positions: [
      {
        id: 'dxy-content',
        title: '医学内容运营实习生',
        department: '丁香医生',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        majors: ['临床医学', '药学'],
        status: 'open',
      },
    ],
    benefits: ['弹性工作', '餐补'],
  },
  {
    id: 'wedoctor-hangzhou',
    kind: 'recruitment',
    name: '微医',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.118, lat: 30.291, address: '余杭区梦想小镇' },
    company: {
      name: '微医',
      industries: ['biotech', 'internet'],
      scale: 'unicorn',
      rating: 3.8,
      logo: '🩺',
      logoUrl: 'https://favicon.im/guahao.com?size=128',
      summary: '数字健康平台',
      careerUrl: 'https://www.guahao.com/job',
    },
    positions: [
      {
        id: 'wedoctor-java',
        title: '后端开发实习生',
        department: '互联网医院',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        skills: ['Java'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'betta-hangzhou',
    kind: 'recruitment',
    name: '贝达药业',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.258, lat: 30.438, address: '临平区兴中路355号' },
    company: {
      name: '贝达药业',
      industries: ['biotech'],
      scale: 'enterprise',
      rating: 3.9,
      logo: '💊',
      logoUrl: 'https://favicon.im/bettapharma.com?size=128',
      summary: '创新药研发与产业化公司',
      careerUrl: 'https://www.bettapharma.com/joinus',
    },
    positions: [
      {
        id: 'betta-ra',
        title: '临床研究助理实习生',
        department: '临床医学',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        majors: ['药学', '临床医学'],
        status: 'open',
      },
    ],
    benefits: ['班车'],
  },
  {
    id: 'tigermed-hangzhou',
    kind: 'recruitment',
    name: '泰格医药',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.213, lat: 30.182, address: '滨江区聚工路19号盛大科技园A座18层' },
    company: {
      name: '泰格医药',
      industries: ['biotech'],
      scale: 'enterprise',
      rating: 3.8,
      logo: '🧬',
      logoUrl: 'https://favicon.im/tigermed.net?size=128',
      summary: '临床试验合同研究组织',
      careerUrl: 'https://www.tigermed.net/careers',
    },
    positions: [
      {
        id: 'tiger-cra',
        title: '临床监查员实习生',
        department: '临床运营',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        majors: ['临床医学'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'robam-hangzhou',
    kind: 'recruitment',
    name: '老板电器',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.299, lat: 30.334, address: '余杭区临平街道江南大道592号' },
    company: {
      name: '老板电器',
      industries: ['consumer', 'hardware'],
      scale: 'enterprise',
      rating: 3.8,
      logo: '🍳',
      logoUrl: 'https://favicon.im/robam.com?size=128',
      summary: '高端厨电品牌',
      careerUrl: 'https://www.robam.com/joinus',
    },
    positions: [
      {
        id: 'robam-me',
        title: '结构工程师实习生',
        department: '研发',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        majors: ['机械'],
        status: 'open',
      },
    ],
    benefits: ['食堂'],
  },
  {
    id: 'supor-hangzhou',
    kind: 'recruitment',
    name: '苏泊尔',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.211, lat: 30.226, address: '滨江区浦沿街道东冠路1782号' },
    company: {
      name: '苏泊尔',
      industries: ['consumer'],
      scale: 'enterprise',
      rating: 3.8,
      logo: '🫖',
      logoUrl: 'https://favicon.im/supor.com.cn?size=128',
      summary: '炊具与小家电品牌',
      careerUrl: 'https://www.supor.com.cn/job',
    },
    positions: [
      {
        id: 'supor-pm',
        title: '产品经理实习生',
        department: '小家电',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'kuka-hangzhou',
    kind: 'recruitment',
    name: '顾家家居',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.352, lat: 30.407, address: '江干区空港经济区泰美国际' },
    company: {
      name: '顾家家居',
      industries: ['consumer'],
      scale: 'enterprise',
      rating: 3.7,
      logo: '🛋️',
      logoUrl: 'https://favicon.im/kukahome.com?size=128',
      summary: '软体家具品牌',
      careerUrl: 'https://www.kukahome.com/join',
    },
    positions: [
      {
        id: 'kuka-ops',
        title: '电商运营实习生',
        department: '天猫',
        type: 'intern',
        salary: { min: 4, max: 6 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'lianlian-hangzhou',
    kind: 'recruitment',
    name: '连连数字',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.109, lat: 30.288, address: '西湖区西溪谷国际商务中心' },
    company: {
      name: '连连数字',
      industries: ['finance', 'internet'],
      scale: 'unicorn',
      rating: 3.8,
      logo: '🔗',
      logoUrl: 'https://favicon.im/lianlianpay.com?size=128',
      summary: '跨境支付与数字金融服务',
      careerUrl: 'https://www.lianlianpay.com/careers',
    },
    positions: [
      {
        id: 'lianlian-risk',
        title: '风控策略实习生',
        department: '风险管理',
        type: 'intern',
        salary: { min: 5, max: 9 },
        education: '本科',
        skills: ['SQL', 'Python'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '下午茶'],
  },
  {
    id: 'souche-hangzhou',
    kind: 'recruitment',
    name: '大搜车',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.118, lat: 30.286, address: '余杭区仓前街道欧美金融城' },
    company: {
      name: '大搜车',
      industries: ['internet', 'automotive'],
      scale: 'unicorn',
      rating: 3.7,
      logo: '🚙',
      logoUrl: 'https://favicon.im/souche.com?size=128',
      summary: '汽车交易数字化服务平台',
      careerUrl: 'https://www.souche.com/jobs',
    },
    positions: [
      {
        id: 'souche-java',
        title: 'Java 开发实习生',
        department: '交易中台',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        skills: ['Java'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'hzbank-hangzhou',
    kind: 'recruitment',
    name: '杭州银行',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.169, lat: 30.253, address: '上城区庆春路46号' },
    company: {
      name: '杭州银行',
      industries: ['finance'],
      scale: 'enterprise',
      rating: 3.9,
      logo: '🏦',
      logoUrl: 'https://favicon.im/hzbank.com.cn?size=128',
      summary: '总部位于杭州的城市商业银行',
      careerUrl: 'https://www.hzbank.com.cn/hzyh/gyyh/rczp/index.html',
    },
    positions: [
      {
        id: 'hzbank-it',
        title: '金融科技管培生',
        department: '科技部',
        type: 'campus',
        taxonomy: { family: 'campus', campusSeason: 'autumn' },
        salary: { min: 8, max: 14 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['补充医疗'],
  },
  {
    id: 'xiaomi-hangzhou',
    kind: 'recruitment',
    name: '小米',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.102, lat: 30.281, address: '西湖区西溪谷G座' },
    company: {
      name: '小米',
      industries: ['hardware', 'internet', 'ai'],
      scale: 'bigtech',
      rating: 4.2,
      logo: '📱',
      logoUrl: 'https://favicon.im/mi.com?size=128',
      summary: '消费电子与智能制造公司',
      careerUrl: 'https://hr.xiaomi.com/',
    },
    positions: [
      {
        id: 'mi-android',
        title: 'Android 开发实习生',
        department: '手机部',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '本科',
        skills: ['Kotlin', 'Android'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '班车'],
  },
  {
    id: 'transsion-hangzhou',
    kind: 'recruitment',
    name: '传音控股',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.118, lat: 30.272, address: '滨江区网商路599号' },
    company: {
      name: '传音控股',
      industries: ['hardware', 'internet'],
      scale: 'enterprise',
      rating: 3.9,
      logo: '📶',
      logoUrl: 'https://favicon.im/transsion.com?size=128',
      summary: '新兴市场智能终端与移动互联网公司',
      careerUrl: 'https://www.transsion.com/career',
    },
    positions: [
      {
        id: 'transsion-android',
        title: 'Android 框架实习生',
        department: 'OS',
        type: 'intern',
        salary: { min: 6, max: 10 },
        education: '本科',
        skills: ['Java', 'Android'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'wasu-hangzhou',
    kind: 'recruitment',
    name: '华数传媒',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.164, lat: 30.274, address: '拱墅区华数大厦' },
    company: {
      name: '华数传媒',
      industries: ['internet', 'content'],
      scale: 'enterprise',
      rating: 3.6,
      logo: '📡',
      logoUrl: 'https://favicon.im/wasu.com.cn?size=128',
      summary: '广电网络与数字媒体公司',
      careerUrl: 'https://www.wasu.com.cn/job',
    },
    positions: [
      {
        id: 'wasu-ops',
        title: '新媒体运营实习生',
        department: '华数TV',
        type: 'intern',
        salary: { min: 4, max: 6 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'insigma-hangzhou',
    kind: 'recruitment',
    name: '浙大网新',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.123, lat: 30.266, address: '西湖区华星路99号创欣大厦' },
    company: {
      name: '浙大网新',
      industries: ['internet', 'hardware'],
      scale: 'enterprise',
      rating: 3.6,
      logo: '🖥️',
      logoUrl: 'https://favicon.im/insigma.com.cn?size=128',
      summary: '行业数字化解决方案公司',
      careerUrl: 'https://www.insigma.com.cn/hr',
    },
    positions: [
      {
        id: 'insigma-java',
        title: 'Java 开发实习生',
        department: '智慧城市',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        skills: ['Java'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'suporlife-hangzhou',
    kind: 'recruitment',
    name: '万事利',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.211, lat: 30.274, address: '上城区万事利大厦' },
    company: {
      name: '万事利',
      industries: ['consumer'],
      scale: 'enterprise',
      rating: 3.6,
      logo: '🧣',
      logoUrl: 'https://favicon.im/wensli.com?size=128',
      summary: '丝绸文化与时尚品牌',
      careerUrl: 'https://www.wensli.com/join',
    },
    positions: [
      {
        id: 'wensli-design',
        title: '视觉设计实习生',
        department: '品牌',
        type: 'intern',
        salary: { min: 4, max: 6 },
        education: '本科',
        majors: ['视觉传达'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'westlake-pharma-hangzhou',
    kind: 'recruitment',
    name: '西湖生物',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.087, lat: 30.196, address: '西湖区云栖小镇' },
    company: {
      name: '西湖生物',
      industries: ['biotech'],
      scale: 'startup',
      rating: 4.0,
      logo: '🧪',
      logoUrl: 'https://favicon.im/westlake.edu.cn?size=128',
      summary: '创新生物医药研发公司',
      careerUrl: 'https://www.westlake.edu.cn/',
    },
    positions: [
      {
        id: 'westlake-ra',
        title: '生物实验助理实习生',
        department: '研发',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        majors: ['生物', '药学'],
        status: 'open',
      },
    ],
    benefits: ['弹性工作'],
  },
  {
    id: 'dt-dream-hangzhou',
    kind: 'recruitment',
    name: '数梦工场',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.108, lat: 30.289, address: '余杭区仓前街道欧美金融城' },
    company: {
      name: '数梦工场',
      industries: ['internet', 'ai'],
      scale: 'unicorn',
      rating: 3.7,
      logo: '☁️',
      logoUrl: 'https://favicon.im/dtdream.com?size=128',
      summary: '城市大脑与政务云公司',
      careerUrl: 'https://www.dtdream.com/join',
    },
    positions: [
      {
        id: 'dtdream-java',
        title: '政务云开发实习生',
        department: '城市大脑',
        type: 'intern',
        salary: { min: 5, max: 9 },
        education: '本科',
        skills: ['Java'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'transfar-hangzhou',
    kind: 'recruitment',
    name: '传化智联',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.278, lat: 30.186, address: '萧山区宁围街道钱江农场传化大厦' },
    company: {
      name: '传化智联',
      industries: ['transport', 'internet'],
      scale: 'enterprise',
      rating: 3.6,
      logo: '🚛',
      logoUrl: 'https://favicon.im/transfar.com?size=128',
      summary: '公路港物流与供应链平台',
      careerUrl: 'https://www.transfar.com/job',
    },
    positions: [
      {
        id: 'transfar-ops',
        title: '供应链运营实习生',
        department: '公路港',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['班车'],
  },
  {
    id: 'eastcom-hangzhou',
    kind: 'recruitment',
    name: '东方通信',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.164, lat: 30.274, address: '滨江区东信大道66号' },
    company: {
      name: '东方通信',
      industries: ['hardware', 'internet'],
      scale: 'enterprise',
      rating: 3.6,
      logo: '📞',
      logoUrl: 'https://favicon.im/eastcom.com?size=128',
      summary: '通信设备与智能终端公司',
      careerUrl: 'https://www.eastcom.com/hr',
    },
    positions: [
      {
        id: 'eastcom-embed',
        title: '通信软件实习生',
        department: '无线',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        skills: ['C', '5G'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'holo-hangzhou',
    kind: 'recruitment',
    name: '非夕科技',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.108, lat: 30.291, address: '余杭区仓前街道欧美金融城' },
    company: {
      name: '非夕科技',
      industries: ['hardware', 'ai'],
      scale: 'startup',
      rating: 4.1,
      logo: '🤖',
      logoUrl: 'https://favicon.im/flexiv.com?size=128',
      summary: '自适应机器人公司',
      careerUrl: 'https://www.flexiv.com/careers',
    },
    positions: [
      {
        id: 'flexiv-robot',
        title: '机器人控制实习生',
        department: '运动控制',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '硕士',
        skills: ['C++', 'ROS'],
        status: 'open',
      },
    ],
    benefits: ['弹性工作'],
  },
  {
    id: 'deepway-hangzhou',
    kind: 'recruitment',
    name: '深势科技',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.098, lat: 30.286, address: '西湖区西溪谷国际商务中心' },
    company: {
      name: '深势科技',
      industries: ['ai', 'biotech'],
      scale: 'unicorn',
      rating: 4.2,
      logo: '⚛️',
      logoUrl: 'https://favicon.im/dp.tech?size=128',
      summary: '科学计算与药物设计公司',
      careerUrl: 'https://www.dp.tech/career',
    },
    positions: [
      {
        id: 'dptech-ml',
        title: '分子模拟算法实习生',
        department: '科研',
        type: 'intern',
        salary: { min: 8, max: 15 },
        education: '硕士',
        majors: ['化学', '物理', '计算机'],
        skills: ['Python', '深度学习'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '弹性工作'],
  },
  {
    id: 'unitree-hangzhou',
    kind: 'recruitment',
    name: '宇树科技',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.221, lat: 30.208, address: '滨江区物联网街' },
    company: {
      name: '宇树科技',
      industries: ['hardware', 'ai'],
      scale: 'unicorn',
      rating: 4.3,
      logo: '🐕',
      logoUrl: 'https://favicon.im/unitree.com?size=128',
      summary: '四足与人形机器人公司',
      careerUrl: 'https://www.unitree.com/cn/career',
    },
    positions: [
      {
        id: 'unitree-ctrl',
        title: '运动控制实习生',
        department: '机器人',
        type: 'intern',
        salary: { min: 7, max: 13 },
        education: '硕士',
        skills: ['C++', '控制理论'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'deepblue-hangzhou',
    kind: 'recruitment',
    name: '云深处科技',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.118, lat: 30.286, address: '余杭区仓前街道' },
    company: {
      name: '云深处科技',
      industries: ['hardware', 'ai'],
      scale: 'startup',
      rating: 4.0,
      logo: '🐾',
      logoUrl: 'https://favicon.im/deeprobotics.cn?size=128',
      summary: '高性能四足机器人公司',
      careerUrl: 'https://www.deeprobotics.cn/join',
    },
    positions: [
      {
        id: 'deeprobo-slam',
        title: 'SLAM 算法实习生',
        department: '感知',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '硕士',
        skills: ['C++', 'SLAM'],
        status: 'open',
      },
    ],
    benefits: ['弹性工作'],
  },
  {
    id: 'manycore-hangzhou',
    kind: 'recruitment',
    name: '群核科技',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.109, lat: 30.293, address: '西湖区余杭塘路515号莱茵·矩阵国际' },
    company: {
      name: '群核科技',
      industries: ['internet', 'ai'],
      scale: 'unicorn',
      rating: 4.0,
      logo: '🏠',
      logoUrl: 'https://favicon.im/kujiale.com?size=128',
      summary: '空间设计云平台（酷家乐）',
      careerUrl: 'https://www.kujiale.com/job',
    },
    positions: [
      {
        id: 'kujiale-3d',
        title: '图形学实习生',
        department: '渲染',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '本科',
        skills: ['C++', 'WebGL'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '下午茶'],
  },
  {
    id: 'dtstack-hangzhou',
    kind: 'recruitment',
    name: '袋鼠云',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.108, lat: 30.288, address: '余杭区仓前街道欧美金融城' },
    company: {
      name: '袋鼠云',
      industries: ['internet', 'ai'],
      scale: 'unicorn',
      rating: 3.8,
      logo: '🦘',
      logoUrl: 'https://favicon.im/dtstack.com?size=128',
      summary: '一站式大数据开发平台',
      careerUrl: 'https://www.dtstack.com/join',
    },
    positions: [
      {
        id: 'dtstack-bigdata',
        title: '大数据开发实习生',
        department: '数栈',
        type: 'intern',
        salary: { min: 5, max: 9 },
        education: '本科',
        skills: ['Java', 'Flink'],
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
  {
    id: 'finogeeks-hangzhou',
    kind: 'recruitment',
    name: '凡泰极客',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.164, lat: 30.258, address: '西湖区文三路259号昌地火炬大厦' },
    company: {
      name: '凡泰极客',
      industries: ['finance', 'internet'],
      scale: 'startup',
      rating: 3.8,
      logo: '📲',
      logoUrl: 'https://favicon.im/finogeeks.com?size=128',
      summary: '银行小程序与开放银行技术公司',
      careerUrl: 'https://www.finogeeks.com/join',
    },
    positions: [
      {
        id: 'fino-fe',
        title: '小程序前端实习生',
        department: 'FinClip',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        skills: ['TypeScript', '小程序'],
        status: 'open',
      },
    ],
    benefits: ['弹性工作'],
  },
];

function withWorkDefaults(poi: RecruitmentPOI): RecruitmentPOI {
  const logo = resolveCompanyLogo({
    siteCareerUrl: poi.company.careerUrl,
    companyLogoUrl: poi.company.logoUrl,
    fallbackEmoji: poi.company.logo,
  });
  const siteId = poi.sites?.[0]?.id ?? `${poi.id}-site`;
  const sites = poi.sites ?? [
    {
      id: siteId,
      name: poi.name,
      location: poi.location,
      careerUrl: poi.company.careerUrl,
      logoUrl: logo.url ?? poi.company.logoUrl,
    },
  ];
  return {
    ...poi,
    mode: 'work',
    company: {
      ...poi.company,
      logo: logo.emoji,
      logoUrl: logo.url ?? poi.company.logoUrl,
    },
    sites,
    positions: poi.positions.map((position) => ({
      ...position,
      siteId: position.siteId ?? siteId,
      taxonomy: position.taxonomy ?? defaultTaxonomyForType(position.type),
    })),
  };
}

/** 工作模式精选公司。INTERNSHIP_SEED 为兼容别名。 */
export const WORK_SEED: RecruitmentPOI[] = WORK_SEED_RAW.map(withWorkDefaults);
export const INTERNSHIP_SEED = WORK_SEED;
