// ============================================================
// 工作模式精选 Seed 数据
//
// 说明：Phase 2 采用"先精选数据、后接数据库"策略。
// 这些是杭州地区知名科技公司的公开位置信息与示例岗位，
// 用于验证工作模式的 UI/筛选/联动逻辑。
//
// 数据合规（tech/08-multi-mode-system.md + agent.md）：
// - 公司位置为公开地理信息，岗位为代表性示例（非实时爬取）
// - 不包含个人简历、联系方式等 PII
// - 生产环境将替换为经 source review 的数据库数据（sources/import_runs）
// ============================================================

import { resolveCompanyLogo } from './company-logo.ts';
import { defaultTaxonomyForType } from './job-taxonomy.ts';
import type { DomainPOI, RecruitmentPOI } from './types.ts';

/**
 * Domain 模式回退种子数据。
 * 用途：AMap JS API 不可用/加载失败时的降级方案（例如首次加载插件竞态、
 * 网络受限环境）。AMap 就绪后，poi-service 会优先返回真实高德 POI。
 * 位置为杭州代表性地点的公开地理信息。
 */
export const DOMAIN_SEED: DomainPOI[] = [
  {
    id: 'hz-westlake',
    kind: 'domain',
    name: '西湖',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.15, lat: 30.242, address: '西湖区龙井路1号' },
    category: '景点',
    subcategory: '自然风光',
    rating: 4.9,
    photos: [],
  },
  {
    id: 'hz-in77',
    kind: 'domain',
    name: '湖滨银泰in77',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.163, lat: 30.256, address: '上城区延安路湖滨' },
    category: '购物',
    subcategory: '购物中心',
    rating: 4.6,
    priceLevel: 3,
    photos: [],
  },
  {
    id: 'hz-louwailou',
    kind: 'domain',
    name: '楼外楼菜馆',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.141, lat: 30.237, address: '西湖区孤山路30号' },
    category: '餐饮',
    subcategory: '杭帮菜',
    rating: 4.3,
    priceLevel: 3,
    openHours: '10:30-21:00',
    photos: [],
  },
  {
    id: 'hz-lingyin',
    kind: 'domain',
    name: '灵隐寺',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.105, lat: 30.24, address: '西湖区法云弄1号' },
    category: '景点',
    subcategory: '佛教文化',
    rating: 4.8,
    photos: [],
  },
  {
    id: 'hz-yinyuequan',
    kind: 'domain',
    name: '音乐泉SPA',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.152, lat: 30.26, address: '西湖区西溪路128号' },
    category: '休闲娱乐',
    subcategory: 'SPA',
    rating: 4.2,
    priceLevel: 4,
    photos: [],
  },
  {
    id: 'hz-wulinsi',
    kind: 'domain',
    name: '武林广场',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.166, lat: 30.269, address: '下城区武林广场' },
    category: '购物',
    subcategory: '商业街区',
    rating: 4.4,
    photos: [],
  },
  {
    id: 'hz-songcheng',
    kind: 'domain',
    name: '杭州宋城',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.083, lat: 30.176, address: '西湖区之江路148号' },
    category: '景点',
    subcategory: '主题公园',
    rating: 4.5,
    priceLevel: 3,
    photos: [],
  },
  {
    id: 'hz-hefangjie',
    kind: 'domain',
    name: '河坊街',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.173, lat: 30.242, address: '上城区河坊街' },
    category: '美食街',
    subcategory: '特色小吃',
    rating: 4.4,
    priceLevel: 2,
    photos: [],
  },
  {
    id: 'hz-xihu-museum',
    kind: 'domain',
    name: '浙江博物馆',
    mode: 'domain',
    source: 'seed',
    location: { lng: 120.146, lat: 30.238, address: '西湖区孤山路25号' },
    category: '文化',
    subcategory: '博物馆',
    rating: 4.6,
    photos: [],
  },
];

const WORK_SEED_RAW: RecruitmentPOI[] = [
  {
    id: 'alibaba-xixi',
    kind: 'recruitment',
    name: '阿里巴巴',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.023, lat: 30.279, address: '余杭区文一西路969号' },
    company: {
      name: '阿里巴巴',
      industries: ['internet', 'ecommerce', 'ai'],
      scale: 'bigtech',
      rating: 4.4,
      logo: '🛰️',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=alibaba.com',
      summary: '全球领先的电子商务与云计算科技公司',
      careerUrl: 'https://talent.alibaba.com/',
    },
    positions: [
      {
        id: 'alibaba-java',
        title: 'Java 后端开发工程师',
        department: '阿里云',
        type: 'intern',
        taxonomy: { family: 'intern', internKind: 'summer', conversion: 'conversion' },
        salary: { min: 8, max: 15 },
        education: '本科',
        majors: ['计算机', '软件工程'],
        skills: ['Java', 'Spring', 'MySQL'],
        description: '参与阿里云核心服务的后端开发，编写高质量 Java 服务，参与需求评审与线上问题排查。熟悉分布式系统优先。',
        apply: { source: 'official', url: 'https://talent.alibaba.com/' },
        status: 'open',
      },
      {
        id: 'alibaba-frontend',
        title: '前端开发工程师',
        department: '淘天集团',
        type: 'intern',
        taxonomy: { family: 'intern', internKind: 'daily', conversion: 'no-conversion' },
        salary: { min: 8, max: 14 },
        education: '本科',
        majors: ['计算机'],
        skills: ['React', 'TypeScript'],
        description: '负责淘天 C 端页面与中后台的前端实现，与设计、后端协作完成需求交付，关注性能与体验。',
        status: 'open',
      },
      {
        id: 'alibaba-ml',
        title: '算法工程师（机器学习）',
        department: '达摩院',
        type: 'intern',
        salary: { min: 10, max: 20 },
        education: '硕士',
        majors: ['计算机', '数学'],
        skills: ['Python', 'PyTorch'],
        description: '参与推荐 / 搜索相关模型训练与评测，阅读论文并落地实验，协助完成数据pipeline 与指标分析。',
        status: 'open',
      },
      {
        id: 'alibaba-product',
        title: '产品经理实习生',
        department: '国际数字商业',
        type: 'intern',
        salary: { min: 6, max: 10 },
        education: '本科',
        description: '协助完成竞品分析、需求文档与用户调研，跟进功能上线，与设计、研发协作推进迭代。',
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车', '健身房', '节日福利'],
  },
  {
    id: 'tencent-hangzhou',
    kind: 'recruitment',
    name: '腾讯',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.155, lat: 30.307, address: '滨江区网商路599号' },
    company: {
      name: '腾讯',
      industries: ['internet', 'game', 'ai'],
      scale: 'bigtech',
      rating: 4.5,
      logo: '🐧',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=tencent.com',
      summary: '中国领先的互联网综合服务提供商',
      careerUrl: 'https://careers.tencent.com/',
    },
    positions: [
      {
        id: 'tencent-backend',
        title: '后台开发工程师',
        department: '腾讯云',
        type: 'campus',
        taxonomy: { family: 'campus', campusSeason: 'autumn' },
        salary: { min: 9, max: 16 },
        education: '本科',
        majors: ['计算机'],
        skills: ['C++', 'Go'],
        status: 'open',
      },
      {
        id: 'tencent-game',
        title: '游戏策划实习生',
        department: '天美工作室',
        type: 'intern',
        salary: { min: 6, max: 10 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车', '下午茶'],
  },
  {
    id: 'netease-hangzhou',
    kind: 'recruitment',
    name: '网易',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.189, lat: 30.187, address: '滨江区网商路599号网易大厦' },
    company: {
      name: '网易',
      industries: ['internet', 'game'],
      scale: 'bigtech',
      rating: 4.3,
      logo: '🎮',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=163.com',
      summary: '中国领先的互联网技术公司，游戏与音乐见长',
      careerUrl: 'https://hr.163.com/',
    },
    positions: [
      {
        id: 'netease-frontend',
        title: '前端开发工程师',
        department: '网易云音乐',
        type: 'campus',
        taxonomy: { family: 'campus', campusSeason: 'spring' },
        salary: { min: 7, max: 12 },
        education: '本科',
        skills: ['React', 'TypeScript'],
        status: 'open',
      },
      {
        id: 'netease-data',
        title: '数据分析师',
        department: '严选',
        type: 'intern',
        salary: { min: 6, max: 10 },
        education: '本科',
        majors: ['统计', '数学'],
        skills: ['SQL', 'Python'],
        status: 'open',
      },
    ],
    benefits: ['免费班车', '健身房', '咖啡'],
  },
  {
    id: 'bytedance-hangzhou',
    kind: 'recruitment',
    name: '字节跳动',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.117, lat: 30.289, address: '余杭区向往街1118号' },
    company: {
      name: '字节跳动',
      industries: ['internet', 'ai', 'ecommerce'],
      scale: 'bigtech',
      rating: 4.6,
      logo: '📱',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=bytedance.com',
      summary: '全球化互联网科技公司，抖音/TikTok 母公司',
      careerUrl: 'https://jobs.bytedance.com/',
    },
    positions: [
      {
        id: 'bytedance-algo',
        title: '推荐算法工程师',
        department: '抖音',
        type: 'intern',
        salary: { min: 10, max: 18 },
        education: '硕士',
        majors: ['计算机'],
        skills: ['Python', '推荐系统'],
        status: 'open',
      },
      {
        id: 'bytedance-ios',
        title: 'iOS 开发工程师',
        department: '抖音',
        type: 'intern',
        salary: { min: 9, max: 16 },
        education: '本科',
        skills: ['Swift', 'Objective-C'],
        status: 'open',
      },
      {
        id: 'bytedance-ops',
        title: '产品运营实习生',
        department: '商业化',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['三餐免费', '免费班车', '健身房', '补充医疗'],
  },
  {
    id: 'huawei-hangzhou',
    kind: 'recruitment',
    name: '华为',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.098, lat: 30.306, address: '滨江区江淑路1000号' },
    company: {
      name: '华为',
      industries: ['hardware', 'ai'],
      scale: 'bigtech',
      rating: 4.2,
      logo: '🌍',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=huawei.com',
      summary: '全球领先的 ICT 基础设施与智能终端提供商',
      careerUrl: 'https://career.huawei.com/',
    },
    positions: [
      {
        id: 'huawei-chip',
        title: '芯片设计工程师',
        department: '海思',
        type: 'social',
        taxonomy: { family: 'social', experience: '1-3' },
        salary: { min: 9, max: 15 },
        education: '硕士',
        majors: ['微电子', '电子工程'],
        apply: { source: 'official', url: 'https://career.huawei.com/' },
        status: 'open',
      },
      {
        id: 'huawei-embedded',
        title: '嵌入式软件工程师',
        department: '2012实验室',
        type: 'intern',
        salary: { min: 8, max: 14 },
        education: '本科',
        skills: ['C', 'Linux'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车', '健身房'],
  },
  {
    id: 'antgroup-hangzhou',
    kind: 'recruitment',
    name: '蚂蚁集团',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.028, lat: 30.273, address: '西湖区天目山路398号' },
    company: {
      name: '蚂蚁集团',
      industries: ['finance', 'internet'],
      scale: 'bigtech',
      rating: 4.3,
      logo: '🐜',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=antgroup.com',
      summary: '领先的数字支付与金融科技公司',
      careerUrl: 'https://talent.antgroup.com/',
    },
    positions: [
      {
        id: 'ant-pay',
        title: '支付后端工程师',
        department: '支付宝',
        type: 'social',
        taxonomy: { family: 'social', experience: '3-5' },
        salary: { min: 9, max: 16 },
        education: '本科',
        skills: ['Java', '分布式'],
        status: 'open',
      },
      {
        id: 'ant-blockchain',
        title: '区块链研发实习生',
        department: '蚂蚁链',
        type: 'intern',
        salary: { min: 8, max: 14 },
        education: '硕士',
        skills: ['Go', 'Rust'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车', '健身'],
  },
  {
    id: 'didi-hangzhou',
    kind: 'recruitment',
    name: '滴滴',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.088, lat: 30.313, address: '余杭区欧美金融城' },
    company: {
      name: '滴滴',
      industries: ['internet', 'transport'],
      scale: 'unicorn',
      rating: 4.0,
      logo: '🚗',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=didiglobal.com',
      summary: '一站式移动出行平台',
      careerUrl: 'https://join.didiglobal.com/',
    },
    positions: [
      {
        id: 'didi-map',
        title: '地图算法实习生',
        department: '地图事业部',
        type: 'social',
        taxonomy: { family: 'social', experience: '0-1' },
        salary: { min: 7, max: 12 },
        education: '硕士',
        skills: ['C++', 'GIS'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '免费班车'],
  },
  {
    id: 'zhihu-hangzhou',
    kind: 'recruitment',
    name: '知乎',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.162, lat: 30.258, address: '西湖区文三路90号东部软件园' },
    company: {
      name: '知乎',
      industries: ['internet', 'ai'],
      scale: 'unicorn',
      rating: 4.1,
      logo: '🧠',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=zhihu.com',
      summary: '中文互联网高质量问答社区',
      careerUrl: 'https://www.zhihu.com/careers',
    },
    positions: [
      {
        id: 'zhihu-nlp',
        title: 'NLP 算法实习生',
        department: 'AI 中心',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '硕士',
        skills: ['Python', 'NLP'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '下午茶'],
  },
  {
    id: 'xixi-ai',
    kind: 'recruitment',
    name: '曦曦AI',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.158, lat: 30.288, address: '余杭区未来科技城' },
    company: {
      name: '曦曦AI',
      industries: ['ai'],
      scale: 'startup',
      rating: 4.0,
      logo: '✨',
      summary: '专注生成式 AI 应用的新锐创业公司',
    },
    positions: [
      {
        id: 'xixi-llm',
        title: '大模型应用开发实习生',
        department: '工程',
        type: 'intern',
        salary: { min: 8, max: 15 },
        education: '本科',
        skills: ['Python', 'LLM', 'RAG'],
        apply: {
          source: 'boss',
          url: 'https://www.zhipin.com/web/geek/job?query=%E6%9B%A6%E6%9B%A6AI%20%E5%A4%A7%E6%A8%A1%E5%9E%8B',
        },
        status: 'open',
      },
    ],
    benefits: ['弹性工作', '股权激励'],
  },
  {
    id: 'deepseek',
    kind: 'recruitment',
    name: '深度求索',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.088, lat: 30.298, address: '滨江区西兴街道物联网街' },
    company: {
      name: '深度求索',
      industries: ['ai'],
      scale: 'unicorn',
      rating: 4.7,
      logo: '🧩',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=deepseek.com',
      summary: 'AI 大模型研发公司，DeepSeek 团队',
      careerUrl: 'https://www.deepseek.com/',
    },
    positions: [
      {
        id: 'deepseek-llm',
        title: '大模型训练实习生',
        department: '研发',
        type: 'intern',
        taxonomy: { family: 'intern', internKind: 'summer', conversion: 'conversion' },
        salary: { min: 12, max: 25 },
        education: '硕士',
        majors: ['计算机', '数学'],
        skills: ['Python', 'PyTorch', '分布式训练'],
        status: 'open',
      },
      {
        id: 'deepseek-infra',
        title: 'AI Infra 工程师',
        department: '基础设施',
        type: 'intern',
        salary: { min: 10, max: 20 },
        education: '本科',
        skills: ['C++', 'CUDA'],
        status: 'open',
      },
    ],
    benefits: ['免费三餐', '顶尖算力'],
  },
  {
    id: 'bilibili-hangzhou',
    kind: 'recruitment',
    name: '哔哩哔哩',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.192, lat: 30.273, address: '西湖区转塘科技园区' },
    company: {
      name: '哔哩哔哩',
      industries: ['internet', 'game'],
      scale: 'bigtech',
      rating: 4.5,
      logo: '📺',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=bilibili.com',
      summary: '中国年轻世代高度聚集的文化社区和视频平台',
      careerUrl: 'https://jobs.bilibili.com/',
    },
    positions: [
      {
        id: 'bili-community',
        title: '社区运营实习生',
        department: '社区',
        type: 'intern',
        salary: { min: 5, max: 8 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['免费班车', '员工餐厅'],
  },
  {
    id: 'futu-hangzhou',
    kind: 'recruitment',
    name: '富途',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.168, lat: 30.247, address: '西湖区古荡街道' },
    company: {
      name: '富途',
      industries: ['finance', 'internet'],
      scale: 'enterprise',
      rating: 4.1,
      logo: '📈',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=futunn.com',
      summary: '一站式数字化金融服务平台',
      careerUrl: 'https://careers.futunn.com/',
    },
    positions: [
      {
        id: 'futu-backend',
        title: '量化系统后端实习生',
        department: '交易系统',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '本科',
        skills: ['Java', 'C++'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '健身房'],
  },
  {
    id: 'hikvision-hangzhou',
    kind: 'recruitment',
    name: '海康威视',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.208, lat: 30.185, address: '滨江区阡陌路555号' },
    company: {
      name: '海康威视',
      industries: ['hardware', 'ai'],
      scale: 'enterprise',
      rating: 4.0,
      logo: '📹',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=hikvision.com',
      summary: '全球领先的智能物联解决方案提供商',
      careerUrl: 'https://career.hikvision.com/',
    },
    positions: [
      {
        id: 'hik-vision',
        title: '计算机视觉算法实习生',
        department: '研究院',
        type: 'intern',
        salary: { min: 7, max: 13 },
        education: '硕士',
        skills: ['Python', 'CV'],
        status: 'open',
      },
    ],
    benefits: ['免费班车', '员工食堂'],
  },
  {
    id: 'megvii-hangzhou',
    kind: 'recruitment',
    name: '旷视科技',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.097, lat: 30.258, address: '西湖区文一西路98号数娱大厦' },
    company: {
      name: '旷视科技',
      industries: ['ai', 'hardware'],
      scale: 'unicorn',
      rating: 4.0,
      logo: '👁️',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=megvii.com',
      summary: '聚焦物联网场景的人工智能公司',
      careerUrl: 'https://www.megvii.com/careers',
    },
    positions: [
      {
        id: 'megvii-face',
        title: '人脸识别算法实习生',
        department: '研究院',
        type: 'intern',
        salary: { min: 7, max: 12 },
        education: '硕士',
        skills: ['Python', 'CV'],
        status: 'open',
      },
    ],
    benefits: ['餐补', '弹性工作'],
  },
  {
    id: 'yuewen-hangzhou',
    kind: 'recruitment',
    name: '阅文集团',
    mode: 'internship',
    source: 'seed',
    location: { lng: 120.117, lat: 30.283, address: '余杭区文一西路998号' },
    company: {
      name: '阅文集团',
      industries: ['internet', 'content'],
      scale: 'enterprise',
      rating: 3.9,
      logo: '📚',
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=yuewen.com',
      summary: '中国领先的网络文学平台',
      careerUrl: 'https://join.yuewen.com/',
    },
    positions: [
      {
        id: 'yuewen-editor',
        title: '内容运营实习生',
        department: '起点读书',
        type: 'intern',
        salary: { min: 4, max: 7 },
        education: '本科',
        status: 'open',
      },
    ],
    benefits: ['餐补'],
  },
];

function withWorkDefaults(poi: RecruitmentPOI): RecruitmentPOI {
  const logo = resolveCompanyLogo({
    siteCareerUrl: poi.company.careerUrl,
    companyLogoUrl: poi.company.logoUrl,
    fallbackEmoji: poi.company.logo,
  });
  return {
    ...poi,
    mode: 'work',
    company: {
      ...poi.company,
      logo: logo.emoji,
      logoUrl: logo.url ?? poi.company.logoUrl,
    },
    positions: poi.positions.map((position) => ({
      ...position,
      taxonomy: position.taxonomy ?? defaultTaxonomyForType(position.type),
    })),
  };
}

/** 工作模式精选公司。INTERNSHIP_SEED 为兼容别名。 */
export const WORK_SEED: RecruitmentPOI[] = WORK_SEED_RAW.map(withWorkDefaults);
export const INTERNSHIP_SEED = WORK_SEED;
